apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80 #Port that other containers in cluster listen to. Also service connects to cluster via this port. #  If another app on cluster is connecting via the name "svc-NodePort", it use this port to connect
      targetPort: 8080 #Port that the app inside the container listens on.
      nodePort: 31111 #Port that external resources can access the app inside the pod
      protocol: TCP
